DEBUG 2025-03-14 13:35:17.879 UTC: 	 CRAB Client version: v3.250217
DEBUG 2025-03-14 13:35:17.879 UTC: 	 Running on: Linux lxplus944.cern.ch 5.14.0-503.23.2.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Feb 7 15:07:19 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-03-14 13:35:17.880 UTC: 	 Not using Singularity
DEBUG 2025-03-14 13:35:17.880 UTC: 	 Operating System: Red Hat Enterprise Linux 9.5 (Plow)
DEBUG 2025-03-14 13:35:17.880 UTC: 	 Executing command: 'status'
DEBUG 2025-03-14 13:35:17.880 UTC: 	 Found CRAB cache file /afs/cern.ch/user/f/fsalerno/.crab3
ERROR 2025-03-14 13:35:17.880 UTC: 	 Error: /afs/cern.ch/user/f/fsalerno/CMSSW_13_2_11/src/PhysicsTools/NanoAODTools/crab/crab_TT_inclusive_2022_topcand is not a valid CRAB project directory.
ERROR 2025-03-14 13:35:17.881 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250217.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250217.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250217.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250217.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250217.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: /afs/cern.ch/user/f/fsalerno/CMSSW_13_2_11/src/PhysicsTools/NanoAODTools/crab/crab_TT_inclusive_2022_topcand is not a valid CRAB project directory.
INFO 2025-03-14 13:35:17.884 UTC: 	 Log file is /afs/cern.ch/user/f/fsalerno/CMSSW_13_2_11/src/PhysicsTools/NanoAODTools/python/postprocessing/machine_learning/Training/crab.log
