/cvmfs/cms.cern.ch/el9_amd64_gcc11/external/py3-numpy/1.23.5-5b6957c965058eaa079a1c3386da7800/lib/python3.9/site-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el9_amd64_gcc11/external/py3-numpy/1.23.5-5b6957c965058eaa079a1c3386da7800/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/cvmfs/cms.cern.ch/el9_amd64_gcc11/external/py3-numpy/1.23.5-5b6957c965058eaa079a1c3386da7800/lib/python3.9/site-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/cvmfs/cms.cern.ch/el9_amd64_gcc11/external/py3-numpy/1.23.5-5b6957c965058eaa079a1c3386da7800/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
2025-06-03 20:28:12.748333: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2025-06-03 20:28:12.748455: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (b9p31p0829.cern.ch): /proc/driver/nvidia/version does not exist
2025-06-03 20:28:12.748889: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/cvmfs/cms.cern.ch/el9_amd64_gcc11/external/py3-keras/2.6.0-a0bd7914a278f603aa4656285bb1112e/lib/python3.9/site-packages/keras/engine/functional.py:582: UserWarning: Input dict contained keys ['PFC'] which did not match any model input. They will be ignored by the model.
  warnings.warn(
sh: line 1: ./haddnano.py: Permission denied
